// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: duo_surface

#ifndef _DUO_SURFACE_UI_H
#define _DUO_SURFACE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

void LeftShow_Animation(lv_obj_t * TargetObject, int delay);
void RightShow_Animation(lv_obj_t * TargetObject, int delay);
void BottomArcShow_Animation(lv_obj_t * TargetObject, int delay);
void BottomPowerShow_Animation(lv_obj_t * TargetObject, int delay);
void BottomSpeedShow_Animation(lv_obj_t * TargetObject, int delay);
void SpinnerHide_Animation(lv_obj_t * TargetObject, int delay);
void IconShow_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Surface
void ui_Surface_screen_init(void);
extern lv_obj_t * ui_Surface;
extern lv_obj_t * ui_SpinnerLoad;
extern lv_obj_t * ui_ContainerTimeLabel;
extern lv_obj_t * ui_LabelTimeTab;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_ContainerDistenceLabel;
extern lv_obj_t * ui_LabelDIstenceTab;
extern lv_obj_t * ui_LabelDistence;
extern lv_obj_t * ui_ContainerCmd;
extern lv_obj_t * ui_RollerCmd;
extern lv_obj_t * ui_LabelCmdTab;
extern lv_obj_t * ui_LabelIcon;
extern lv_obj_t * ui_ArcPower;
extern lv_obj_t * ui_ArcSpeed;
extern lv_obj_t * ui_LabelPower;
extern lv_obj_t * ui_LabelSpeed;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_CmdFont);
LV_FONT_DECLARE(ui_font_IconFont);
LV_FONT_DECLARE(ui_font_SubCmdFont);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
