// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: duo_surface

#ifndef _UI_COMP_CONTAINERTIMELABEL_H
#define _UI_COMP_CONTAINERTIMELABEL_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ContainerTImeLabel
#define UI_COMP_CONTAINERTIMELABEL_CONTAINERTIMELABEL 0
#define _UI_COMP_CONTAINERTIMELABEL_NUM 1
lv_obj_t * ui_ContainerTImeLabel_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
