// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: duo_surface

#include "ui.h"


// COMPONENT ContainerTImeLabel

lv_obj_t * ui_ContainerTImeLabel_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ContainerTImeLabel;
    cui_ContainerTImeLabel = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_ContainerTImeLabel);
    lv_obj_set_width(cui_ContainerTImeLabel, 100);
    lv_obj_set_height(cui_ContainerTImeLabel, 50);
    lv_obj_set_x(cui_ContainerTImeLabel, -87);
    lv_obj_set_y(cui_ContainerTImeLabel, -83);
    lv_obj_set_align(cui_ContainerTImeLabel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_ContainerTImeLabel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINERTIMELABEL_NUM);
    children[UI_COMP_CONTAINERTIMELABEL_CONTAINERTIMELABEL] = cui_ContainerTImeLabel;
    lv_obj_add_event_cb(cui_ContainerTImeLabel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ContainerTImeLabel, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ContainerTImeLabel_create_hook(cui_ContainerTImeLabel);
    return cui_ContainerTImeLabel;
}

