// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: duo_surface

#include "ui.h"


// COMPONENT ContainerCmd

lv_obj_t * ui_ContainerCmd_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ContainerCmd;
    cui_ContainerCmd = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_ContainerCmd);
    lv_obj_set_width(cui_ContainerCmd, 100);
    lv_obj_set_height(cui_ContainerCmd, 50);
    lv_obj_set_x(cui_ContainerCmd, 69);
    lv_obj_set_y(cui_ContainerCmd, -28);
    lv_obj_set_align(cui_ContainerCmd, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_ContainerCmd, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINERCMD_NUM);
    children[UI_COMP_CONTAINERCMD_CONTAINERCMD] = cui_ContainerCmd;
    lv_obj_add_event_cb(cui_ContainerCmd, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ContainerCmd, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ContainerCmd_create_hook(cui_ContainerCmd);
    return cui_ContainerCmd;
}

