// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: duo_surface

#include "ui.h"


// COMPONENT ContainerDistenceLabel

lv_obj_t * ui_ContainerDistenceLabel_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ContainerDistenceLabel;
    cui_ContainerDistenceLabel = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_ContainerDistenceLabel);
    lv_obj_set_width(cui_ContainerDistenceLabel, 100);
    lv_obj_set_height(cui_ContainerDistenceLabel, 50);
    lv_obj_set_align(cui_ContainerDistenceLabel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_ContainerDistenceLabel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINERDISTENCELABEL_NUM);
    children[UI_COMP_CONTAINERDISTENCELABEL_CONTAINERDISTENCELABEL] = cui_ContainerDistenceLabel;
    lv_obj_add_event_cb(cui_ContainerDistenceLabel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ContainerDistenceLabel, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ContainerDistenceLabel_create_hook(cui_ContainerDistenceLabel);
    return cui_ContainerDistenceLabel;
}

