// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: duo_surface

#ifndef _DUO_SURFACE_UI_COMP_HOOK_H
#define _DUO_SURFACE_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_ContainerCmd_create_hook(lv_obj_t * comp);
void ui_comp_ContainerDistenceLabel_create_hook(lv_obj_t * comp);
void ui_comp_ContainerTImeLabel_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
