// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: duo_surface

#ifndef _UI_COMP_CONTAINERCMD_H
#define _UI_COMP_CONTAINERCMD_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ContainerCmd
#define UI_COMP_CONTAINERCMD_CONTAINERCMD 0
#define _UI_COMP_CONTAINERCMD_NUM 1
lv_obj_t * ui_ContainerCmd_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
