// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: duo_surface

#ifndef _UI_COMP_CONTAINERDISTENCELABEL_H
#define _UI_COMP_CONTAINERDISTENCELABEL_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ContainerDistenceLabel
#define UI_COMP_CONTAINERDISTENCELABEL_CONTAINERDISTENCELABEL 0
#define _UI_COMP_CONTAINERDISTENCELABEL_NUM 1
lv_obj_t * ui_ContainerDistenceLabel_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
