// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: duo_surface

#include "ui.h"

void getListAndPlayAnimation(lv_event_t * e)
{
	extern char* list;
	list = "65米\n右转\n1.3公里\n左转\n59米\n右转\n2.1公里\n左转\n3.1公里\n右转\n800米\n左转\n1.5公里";//get list from python
	lv_roller_set_options(ui_RollerCmd, list, LV_ROLLER_MODE_NORMAL);//load list
	
	//start animation
	int base = 2000;
	SpinnerHide_Animation(ui_SpinnerLoad, base + 0);
	LeftShow_Animation(ui_ContainerTimeLabel, base + 100);
	LeftShow_Animation(ui_ContainerDistenceLabel, base + 300);
	RightShow_Animation(ui_ContainerCmd, base + 100);
	BottomArcShow_Animation(ui_ArcPower, base + 300);
	BottomArcShow_Animation(ui_ArcSpeed, base + 300);
	BottomPowerShow_Animation(ui_LabelPower, base + 500);
	BottomSpeedShow_Animation(ui_LabelSpeed, base + 500);
	IconShow_Animation(ui_LabelIcon, base + 300);
}
