// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: duo_surface

#include "ui.h"

void ui_Surface_screen_init(void)
{
    ui_Surface = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Surface, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_Surface, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Surface, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Surface, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Surface, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinnerLoad = lv_spinner_create(ui_Surface, 1000, 90);
    lv_obj_set_width(ui_SpinnerLoad, 120);
    lv_obj_set_height(ui_SpinnerLoad, 120);
    lv_obj_set_align(ui_SpinnerLoad, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpinnerLoad, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_SpinnerLoad, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpinnerLoad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpinnerLoad, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SpinnerLoad, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpinnerLoad, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpinnerLoad, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ContainerTimeLabel = ui_ContainerTImeLabel_create(ui_Surface);
    lv_obj_set_height(ui_ContainerTimeLabel, 24);
    lv_obj_set_width(ui_ContainerTimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ContainerTimeLabel, -150);
    lv_obj_set_y(ui_ContainerTimeLabel, 5);
    lv_obj_set_align(ui_ContainerTimeLabel, LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(ui_ContainerTimeLabel,
                      LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_LabelTimeTab = lv_label_create(ui_ContainerTimeLabel);
    lv_obj_set_width(ui_LabelTimeTab, 5);
    lv_obj_set_height(ui_LabelTimeTab, 24);
    lv_label_set_text(ui_LabelTimeTab, "");
    lv_obj_set_style_bg_color(ui_LabelTimeTab, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelTimeTab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime = lv_label_create(ui_ContainerTimeLabel);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime, 12);
    lv_obj_set_y(ui_LabelTime, 0);
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelTime, "1:23:45");
    lv_obj_clear_flag(ui_LabelTime, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LabelTime, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTime, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerDistenceLabel = ui_ContainerDistenceLabel_create(ui_Surface);
    lv_obj_set_height(ui_ContainerDistenceLabel, 24);
    lv_obj_set_width(ui_ContainerDistenceLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ContainerDistenceLabel, -150);
    lv_obj_set_y(ui_ContainerDistenceLabel, 35);
    lv_obj_set_align(ui_ContainerDistenceLabel, LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(ui_ContainerDistenceLabel, LV_OBJ_FLAG_HIDDEN);      /// Flags
    lv_obj_set_style_pad_left(ui_ContainerDistenceLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerDistenceLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerDistenceLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerDistenceLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDIstenceTab = lv_label_create(ui_ContainerDistenceLabel);
    lv_obj_set_width(ui_LabelDIstenceTab, 5);
    lv_obj_set_height(ui_LabelDIstenceTab, 24);
    lv_label_set_text(ui_LabelDIstenceTab, "");
    lv_obj_set_style_bg_color(ui_LabelDIstenceTab, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelDIstenceTab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDistence = lv_label_create(ui_ContainerDistenceLabel);
    lv_obj_set_width(ui_LabelDistence, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDistence, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDistence, 12);
    lv_obj_set_y(ui_LabelDistence, 0);
    lv_obj_set_align(ui_LabelDistence, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelDistence, "12.345km");
    lv_obj_set_style_text_color(ui_LabelDistence, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDistence, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelDistence, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDistence, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCmd = ui_ContainerCmd_create(ui_Surface);
    lv_obj_set_width(ui_ContainerCmd, 90);
    lv_obj_set_height(ui_ContainerCmd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ContainerCmd, 150);
    lv_obj_set_y(ui_ContainerCmd, -145);
    lv_obj_set_align(ui_ContainerCmd, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_ContainerCmd, LV_OBJ_FLAG_HIDDEN);      /// Flags

    ui_RollerCmd = lv_roller_create(ui_ContainerCmd);
    lv_roller_set_options(ui_RollerCmd,
                          "无",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_RollerCmd, 2, LV_ANIM_OFF);
    lv_obj_set_width(ui_RollerCmd, 85);
    lv_obj_set_height(ui_RollerCmd, 120);
    lv_obj_set_align(ui_RollerCmd, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_RollerCmd, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_clear_flag(ui_RollerCmd, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_RollerCmd, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerCmd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_RollerCmd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_RollerCmd, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerCmd, &ui_font_SubCmdFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerCmd, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerCmd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RollerCmd, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RollerCmd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RollerCmd, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerCmd, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_RollerCmd, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_RollerCmd, 3, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerCmd, &ui_font_CmdFont, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerCmd, lv_color_hex(0x4040FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerCmd, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_LabelCmdTab = lv_label_create(ui_ContainerCmd);
    lv_obj_set_width(ui_LabelCmdTab, 5);
    lv_obj_set_height(ui_LabelCmdTab, 24);
    lv_obj_set_align(ui_LabelCmdTab, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelCmdTab, "");
    lv_obj_set_style_bg_color(ui_LabelCmdTab, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelCmdTab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIcon = lv_label_create(ui_Surface);
    lv_obj_set_width(ui_LabelIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIcon, 0);
    lv_obj_set_y(ui_LabelIcon, -20);
    lv_obj_set_align(ui_LabelIcon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIcon, "");
    lv_obj_set_style_text_color(ui_LabelIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIcon, &ui_font_IconFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_LabelIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcPower = lv_arc_create(ui_Surface);
    lv_obj_set_width(ui_ArcPower, 175);
    lv_obj_set_height(ui_ArcPower, 175);
    lv_obj_set_x(ui_ArcPower, 0);
    lv_obj_set_y(ui_ArcPower, 320);
    lv_obj_set_align(ui_ArcPower, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcPower, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE);     /// Flags
    lv_arc_set_value(ui_ArcPower, 80);
    lv_arc_set_bg_angles(ui_ArcPower, 190, 350);
    lv_obj_set_style_arc_color(ui_ArcPower, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcPower, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcPower, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcPower, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcPower, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcPower, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcPower, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_ArcPower, LV_BLEND_MODE_MULTIPLY, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ArcPower, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcSpeed = lv_arc_create(ui_Surface);
    lv_obj_set_width(ui_ArcSpeed, 210);
    lv_obj_set_height(ui_ArcSpeed, 210);
    lv_obj_set_x(ui_ArcSpeed, 0);
    lv_obj_set_y(ui_ArcSpeed, 320);
    lv_obj_set_align(ui_ArcSpeed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcSpeed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE);     /// Flags
    lv_arc_set_range(ui_ArcSpeed, 0, 50);
    lv_arc_set_value(ui_ArcSpeed, 20);
    lv_arc_set_bg_angles(ui_ArcSpeed, 190, 350);
    lv_obj_set_style_arc_color(ui_ArcSpeed, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcSpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcSpeed, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcSpeed, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcSpeed, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcSpeed, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcSpeed, 22, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcSpeed, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_ArcSpeed, LV_BLEND_MODE_MULTIPLY, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ArcSpeed, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelPower = lv_label_create(ui_Surface);
    lv_obj_set_width(ui_LabelPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPower, 0);
    lv_obj_set_y(ui_LabelPower, 200);
    lv_obj_set_align(ui_LabelPower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPower, "80%");
    lv_obj_clear_flag(ui_LabelPower, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelPower, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPower, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSpeed = lv_label_create(ui_Surface);
    lv_obj_set_width(ui_LabelSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeed, 0);
    lv_obj_set_y(ui_LabelSpeed, 200);
    lv_obj_set_align(ui_LabelSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeed, "20");
    lv_obj_clear_flag(ui_LabelSpeed, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeed, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

}
